version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spinwheel_app
    ports:
      - "3000:3000"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
      - /app/frontend/node_modules
      - /app/frontend/build
    environment:
      - NODE_ENV=production
      - REACT_APP_CONTRACT_ADDRESS=0x7AfDFa822e0Ef8089D0dF7bad6ECB0d8D4c2d664
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3