import { cookieStorage, createStorage } from 'wagmi'
import { WagmiAdapter } from '@reown/appkit-adapter-wagmi'
import { defineChain } from 'viem'

// Define Monad Mainnet chain
export const monadMainnet = defineChain({
  id: 143,
  name: 'Monad',
  network: 'monad',
  nativeCurrency: {
    decimals: 18,
    name: 'MON',
    symbol: 'MON',
  },
  rpcUrls: {
    default: {
      http: [
        'https://rpc.monad.xyz',
        'https://rpc1.monad.xyz',
        'https://rpc2.monad.xyz',
        'https://rpc3.monad.xyz',
        process.env.RPC_URL || 'https://testnet.monad.xyz',
      ],
    },
    public: {
      http: [
        'https://rpc.monad.xyz',
        'https://rpc1.monad.xyz',
        'https://rpc2.monad.xyz',
        'https://rpc3.monad.xyz',
        process.env.RPC_URL || 'https://testnet.monad.xyz',
      ],
    },
  },
  blockExplorers: {
    default: {
      name: 'Monad Explorer',
      url: 'https://monadexplorer.com',
    },
  },
  iconUrl: '/unicorn/monad-logo.png',
  testnet: false,
})

// Read Project ID from environment variables
export const projectId = process.env.REACT_APP_PROJECT_ID || process.env.NEXT_PUBLIC_PROJECT_ID

// Ensure Project ID is defined at build time
if (!projectId) {
  throw new Error('Project ID is not defined. Please set REACT_APP_PROJECT_ID or NEXT_PUBLIC_PROJECT_ID in .env.local')
}

// Define supported networks - Monad Mainnet only
export const networks = [monadMainnet]

// Create the Wagmi adapter instance
export const wagmiAdapter = new WagmiAdapter({
  storage: createStorage({ storage: cookieStorage }),
  ssr: false, // This is a CRA app, not Next.js
  projectId,
  networks,
  // Polling interval for block watching (10 seconds is reasonable)
  pollingInterval: 10_000,
})

// Export the Wagmi config generated by the adapter
export const config = wagmiAdapter.wagmiConfig